# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test-clock:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: 
          command: sudo apt update && sudo apt install cloc
      - run: cloc . --json
  test-docker:
    docker:
      - image: aldanial/cloc:latest
    steps:
      - checkout
      - run: cloc .
      
workflows:
  test:
    jobs:
      - test-docker
      - test-clock
      
