# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ksember-orb: klsember/test-orb@dev:21c8886

jobs:
  #test-apt:
  #  docker:
  #    - image: cimg/node:17.1.0
  #  steps:
  #    - checkout
  #    - run: 
  #        command: sudo apt update && sudo apt install cloc
  #    - run: cloc . --json
  test-npm:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: sudo npm install -g cloc
      - run: cloc . --json
      - run: cloc --diff /home/circleci/project /home/circleci/project/ui
  #test-docker:
  #  docker:
  #    - image: aldanial/cloc:latest
  #  steps:
  #    - run: 
  #        command: |
  #          /usr/src/cloc . --json
  #          export PATH="/usr/src:$PATH"
  #          cloc . --json

      
workflows:
  test:
    jobs:
      - test-npm
      # - test-apt
      # - test-docker
      
      
