# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ksember-orb: klsember/test-orb@dev:21c8886

jobs:
  test-clock:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: 
          command: sudo apt update && sudo apt install cloc
      - run: cloc . --json
  test-docker:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: sudo npm install -g cloc
      - run: cloc .
  test-dev-orb:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ksember-orb/greet
      
workflows:
  test:
    jobs:
      - test-docker
      - test-clock
      - test-dev-orb
      
      
