# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  test-orb: klsember/test-orb@dev:alpha

jobs:
  test-clock:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: 
          command: npm install -g cloc
      - run: cloc . --json
      
workflows:
  test:
    jobs:
      - test-clock
      - test-orb/greet
      
